export default {
  extends: ['@commitlint/config-conventional'],
  ignores: [(msg) => msg.includes('WIP') || msg.includes('init')],
  rules: {
    'body-leading-blank': [2, 'always'],
    'body-max-length': [2, 'always', 'Infinity'],
    'body-max-line-length': [2, 'always', 100],
    'body-min-length': [2, 'always', 30],
    'footer-leading-blank': [2, 'always'],
    'header-max-length': [2, 'always', 100],
    'header-min-length': [2, 'always', 15],
    'scope-case': [2, 'always', ['lower-case', 'upper-case']],
    'scope-empty': [2, 'never'],
    'scope-max-length': [2, 'always', 12],
    'subject-empty': [2, 'never'],
    'subject-max-length': [2, 'always', 80],
    'type-case': [2, 'always', 'lower-case'],
    'type-empty': [2, 'never'],
    'type-enum': [
      2,
      'always',
      [
        'feat',
        'fix',
        'docs',
        'style',
        'refactor',
        'perf',
        'test',
        'build',
        'ci',
        'chore',
        'revert',
        'remove',
      ],
    ],
  },
};
